import type { Metadata, Viewport } from "next"

import { inter } from "@/fonts"
import "@/styles/globals.css"

export const metadata: Metadata = {
  title: {
    template: "%s | Acme",
    default: "Acme",
  },
  description: "Generated by create next app",
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#fafafa" }, // zinc-50
    { media: "(prefers-color-scheme: dark)", color: "#09090b" }, // zinc-950
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body>{children}</body>
    </html>
  )
}
